### ISSUE TITLE
obs2mk attempts to delete the docs folder and causes an IsADirectory exception

### ISSUE THREAD

**Issue by ProfDoof** [Mara-Li/mkdocs_obsidian_publish#1]
I am attempting to setup obs2mk right now and every time that I try to run the command I get the following exception:
```
Traceback (most recent call last):
  File "/home/john/ObsidianPages/StarshipsAndShannons/bin/obs2mk", line 8, in <module>
    sys.exit(main())
  File "/home/john/ObsidianPages/StarshipsAndShannons/lib/python3.8/site-packages/mkdocs_obsidian/__main__.py", line 81, in main
    info = check.delete_not_exist()
  File "/home/john/ObsidianPages/StarshipsAndShannons/lib/python3.8/site-packages/mkdocs_obsidian/common/file_checking.py", line 38, in delete_not_exist
    os.remove(Path(file))
IsADirectoryError: [Errno 21] Is a directory: '/home/john/ObsidianPages/StarshipsAndShannons/docs'
```

Digging around a bit turned up that the `glob.iglob()` that is being used to iterate over the folder is returning the docs folder and then the script attempts to delete the folder with `os.remove()` which causes problems. I'm not exactly sure whether I'm doing something wrong here in my setup of the obs2mk configuration that is causing this problem but if so I would appreciate any guidance possible. 

To facilitate better help I'll run through what I have done in order to set this up.
1. I set up a new folder that will be for the pages that I will be publishing at the absolute path `/home/username/ObsidianPages`
2. I cloned your template that I copied into `/home/username/ObsidianPages/vaultname`
3. I set up a python virtual environment in that folder so that I wouldn't pollute my global python space with the packages I needed to install.
4. I activated my virtualenv using `source bin/activate` inside of the template folder
5. I installed all of the prerequisites using `pip install -r requirements.txt`
6. I ran the obs2mk command
7. I provided the vault path as `/home/username/ObsidianVaults/vaultname/vaultname`
8. I provided the blog path as `/home/username/ObsidianPages/vaultname`

After that, it then ran some of the common code and I got the exception specified above

**Comment by Mara-Li** [comment]
It's strange because normally, the glob run IN docs. So I don't understand what is causing this issue. 

On which plateform do you run the script? 

I didn't saw anything in your configuration that can cause this issue... 
The best way to debug it is to clone the script ans print what is the path ran by iglob. 

Do you know how to do that? I can provide a test branch you can clone to test (as I can't repro the issue).

**Comment by ProfDoof** [comment]
I am running it on Ubuntu 20.04 with Python 3.9

**Comment by ProfDoof** [comment]
And I did test it by editing the python script in my virtual environments site wide packages. Had it print out the paths it looked at and it printed (this is from memory cuz I'm about to go to bed and on mobile)
```
/home/username/ObsidianPages/vaultname/docs
/home/username/ObsidianPages/vaultname/docs/thing1
/home/username/ObsidianPages/vaultname/docs/thing2
```

**Comment by Mara-Li** [comment]
Hmmm, I think it's because on windows, it raises PermissionError, but not on Linux, where IsADirectoryError is raised. 

You can edit the function to that : 
```python
def delete_not_exist():
    vault_file = []
    info = []
    excluded = []
    important_folder = ["assets", "css", "js", "logo", "script"]
    docs = Path(f"{BASEDIR}/docs/**")
    for i, j, k in os.walk(vault):
        for ki in k:
            vault_file.append(os.path.basename(ki))
            if exclude.exclude_folder(i + os.sep + ki):
                excluded.append(os.path.basename(ki))
    for file in glob.iglob(docs, recursive=True):
        if not (any(i in file for i in important_folder)):
            if not re.search("(index|CNAME)", os.path.basename(file)) and (
                os.path.basename(file) not in vault_file
                or os.path.basename(file) in excluded
            ):  # or if file in file_excluded
                try:
                    os.remove(Path(file))
                    info.append(os.path.basename(file))
                except PermissionError:
                    pass
                except IsADirectoryError:
                    pass
    return info
```

**Comment by ProfDoof** [comment]
I ended up just adding docs to the `important_folder` list. However, would it be ok to make a PR with some of these changes?

**Comment by Mara-Li** [comment]
I think excluded could work too !
I was too much busy today, but I will update the script. It's pretty strange that you have this error, and not me. I think I can add more checkup for the deletion, too.

**Comment by Mara-Li** [comment]
Could you try the new version ? I made some change to this behavior.

**Comment by ProfDoof** [comment]
Ok, I'll check that out in a bit. I'm in the middle of writing a python markdown extension to support Extended Table format. :sweat_smile:

**Comment by Mara-Li** [comment]
Ho, it's a pretty nice idea ! Good luck with that !

**Comment by ProfDoof** [comment]
I'm done with the extension and have checked the obs2mk tool. It seems to be working now that I've updated it to 0.2.10.

**Comment by Mara-Li** [comment]
Perfect ! I close the issue.
