### ISSUE TITLE
Invalid `blog_path` prevents any more changes

### ISSUE THREAD

**Issue by KucharczykL** [Mara-Li/mkdocs_obsidian_publish#2]
When setting `obs2mk` for the first time, I've entered an invalid path (`docs`) and no matter what I tried, there was an error message:

```bash
> obs2mk --config
Traceback (most recent call last):
  File "/home/lukas/.local/bin/obs2mk", line 5, in <module>
    from mkdocs_obsidian.__main__ import main
  File "/home/lukas/.local/lib/python3.10/site-packages/mkdocs_obsidian/__main__.py", line 13, in <module>
    from mkdocs_obsidian.common import (
  File "/home/lukas/.local/lib/python3.10/site-packages/mkdocs_obsidian/common/config.py", line 117, in <module>
    img.mkdir(exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1173, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'docs/docs/assets/img'
```

I had to find and manually edit `.mkdocs_obsidian` before I could do anything. It is also not easy to find the `.mkdocs_obsidian` file; it strikes me as intuitive that it's saved in the Python package folder.

**Comment by Mara-Li** [comment]
Thanks! I was pretty sure I saw this error sometimes, but never success to catch the behavior. 

To explain: Even when running the configuration program, it was looking for some folders before creation, during the original import of the script. As a result, it was giving an error, preventing the configuration program (and all others) from running.

So, I made the program quit automatically when the environment is created, whatever the command launched. Also, it is no longer possible to put anything as a folder during the configuration. 

---

For the configuration path, I corrected the readme with the good path : `site_package/mkdocs_obsidian`, not just `site_package`. 
Sorry for this!

**Comment by KucharczykL** [comment]
Thank you for such a fast fix!

**Comment by Studentenfutter** [comment]
In the same regard: When starting `obs2mk` I get a missing module error: 
```
ModuleNotFoundError: No module named 'rich'
```
Running `pip install rich` fixed the issue.

**Comment by Mara-Li** [comment]
Yeah, I forgot to change the requirements in setup.py. I will update this to get directly from requirements.txt, because I always forgot to change this second import !
