### ISSUE TITLE
[FR]multiple configurations

### ISSUE THREAD

**Issue by suky57** [Mara-Li/mkdocs_obsidian_publish#6]
**Is your feature request related to a problem? Please describe.**
I need to generate multiple sites from Obsidian vault howover script so far supports only one generic configuration.

**Describe the solution you'd like**
add the attribute to specify ad-hoc configuration file

**Describe alternatives you've considered**
write script to "switch" the configurations - not elegant way

**Comment by suky57** [comment]
yep, that sounds great!

**Comment by Mara-Li** [comment]
I will do that when I can ! Sorry for the time i will take ^^

**Comment by suky57** [comment]
no worries, take your time. In the meantime I will write down the nasty script to make the switch happen

**Comment by Mara-Li** [comment]
Hello! I created the feature request. I try it without problem, but I prefer that you test it before I merge to the main branch !

You can try it using the branch dev : `pip install git+https://github.com/Mara-Li/mkdocs_obsidian_publish.git@dev`

**Comment by Mara-Li** [comment]
Also, I change every commands, so to create different configuration file : 
`obs2mk config --new configname`
to use it : 
- For all vault : `obs2mk --use configname all` or just `obs2mk --use configname`
- For one file : `obs2mk --use configname file FILEPATH` 

Here is the documentation : 

Global options :
- `--git` : No commit and push to git ; 
- `--mobile` : Use mobile shortcuts instead of `--git`
- `--meta` : Update frontmatter of source files
- `--keep` : Don't delete files in blog folder
- `--shell` : Remove Rich printing

Commands and specific options :
- **config** : (*it will ignore `--use configuration_name`*)
    - `--new configuration_name` : Create a specific configuration for some files
- **all** : Share all vault
    - `--force` : Force updating (ignore the difference between the source and blog file)
    - `--vault` : Share all vault file, ignoring the share state.
- **`file [file*]`** : Share only one file

The order is : 
`obs2mk global_options [config | all | file] (specific options)`

**Comment by suky57** [comment]
Hello,

seems there is some bug. I installed the @dev version (MacOS + Python3.9):

***@***.*** blog % obs2mk
Traceback (most recent call last):
  File "/usr/local/bin/obs2mk", line 5, in <module>
    from mkdocs_obsidian.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/mkdocs_obsidian/__main__.py", line 18, in <module>
    from mkdocs_obsidian.common import (
  File "/usr/local/lib/python3.9/site-packages/mkdocs_obsidian/common/convert_all.py", line 18, in <module>
    from mkdocs_obsidian.common import (
  File "/usr/local/lib/python3.9/site-packages/mkdocs_obsidian/common/file_checking.py", line 286, in <module>
    def delete_file(filepath: str, folder: str|Path, meta_update=1) -> bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'


S pozdravem / Kind regards

Martin Sukaný
UNIX Engineer, Developer, DevOps specialist
https://www.sukany.cz

Matrix: ***@***.***
SIP: ***@***.***
Phone: +420 577 544 796
E-mail: ***@***.***
LinkedIn: https://www.linkedin.com/in/martins6

**Comment by Mara-Li** [comment]
It appears that a problem with docstring and everything! I will clear all, thanks for the report. :)

**Comment by Mara-Li** [comment]
Oh, strange behavior. Is the folder “Hidden” created too? And the folder `hidden` exists?

**Comment by suky57** [comment]
Just one ‘hidden’ folder exists inside the docs howover ‘Hidden’ (with capital h) is visible at the sites. Not sure if the issue is directly related with obs2mk, template or mkdocs itself - do you know what exactly causes that hidden folder is not being visible? I’d try to figure out where exactly is the problem.




S pozdravem / Kind regards

Martin Sukaný
UNIX Engineer, Developer, DevOps specialist
https://www.sukany.cz

Matrix: ***@***.***
SIP: ***@***.***
Phone: +420 577 544 796
E-mail: ***@***.***
LinkedIn: https://www.linkedin.com/in/martins6

**Comment by suky57** [comment]
Ah, here we are … I used your template but without ./docs - so basicaly the hidden folder was created without .pages specification. Now it seems ok :) 


S pozdravem / Kind regards

Martin Sukaný
UNIX Engineer, Developer, DevOps specialist
https://www.sukany.cz

Matrix: ***@***.***
SIP: ***@***.***
Phone: +420 577 544 796
E-mail: ***@***.***
LinkedIn: https://www.linkedin.com/in/martins6

**Comment by Mara-Li** [comment]
Perfect in this case ! 
i will merge the branches :)
